version: "3.8"

services:
  python_api:
    container_name: python_api
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .env
    volumes:
      - ./openai_data_log.sqlite3:/code/openai_data_log.sqlite3
